export enum PAGES {
  HOME = "HOME",
  BLOG = "BLOG",
  VACANCIES = "VACANCIES",
  OUR_ALLIES = "OUR_ALLIES",
  OUR_CLIENTS = "OUR_CLIENTS",
  SUCCESS_CASES = "SUCCESS_CASES",
  MEMBERSHIPS = "MEMBERSHIPS"
}
