import { ICredential } from "./administrator";
import { IBusinessType } from "./IBusinessType";
import { IUser } from "./IUser";

export interface IBusiness {
  email: string;
  username: string;
  id: number;
  credentialUserId: number;
  firstName: string;
  secondName: string;
  lastName: string;
  secondLastName: string;
  telephone: string;
  cellphone: string;
  identificationTypeId: number;
  identification: string;
  cityId: number;
  stateId: number;
  age: number;
  languages: string[];
  maritalStatusId: number;
  image?: string;
  cv?: any;
  birthday: string;
  address: string;
  completedProfile: boolean;
  completePercent: number;
  userTypeId: number;
  placeIdentificationState: number;
  placeIdentificationCity: number;
  identificationIssueDate: string;
  militaryCard: boolean;
  militaryCardNumber: number;
  bloodTypesId: number;
  placeResidenceState: number;
  placeResidenceCity: number;
  district: string;
  stratum: number;
  housingType: string;
  authorizeCompanyData: boolean;
  height: number;
  weight: number;
  dependents: number;
  facebook: string;
  twitter: string;
  instagram: string;
  linkedin: string;
  minimumSalary: number;
  maxSalary: number;
  availabilityTravel: boolean;
  workdayId: number;
  longitude?: any;
  latitude?: any;
  distance?: any;
  createdAt: string;
  updatedAt: string;
  deletedAt?: any;
  maritalGenderId: number;
  availabilityToRelocation: boolean;
  peopleDiscapacity: boolean;
  drivingLicenseId: number;
  credentialCompanyId: number;
  credentialCompany: {
    credentialUser?: IUser,
    email:string,
    id: number,
  };
  businessTypeId: number;
  businessType: IBusinessType;
  name: string;
  nit: string;
  ciiu: string;
  economicActivity: string;
  typeOfTaxPayer: string;
  retainerTitleRent: string;
  telephones: string;
  legalRepresentativeName: string;
  dniLegalRepresentative: string;
  expeditionCityId: number;
  contactName: string;
  positionContact: string;
  cellphoneContact: string;
  telephoneContact: string;
  extTelephoneContact: string;
  emailContact?: any;
  numberWorkers: string;
  mission: string | null;
  vision: string | null;
  principles: string | null;
  numberWorkersDirect: string;
  numberWorkersTemporals: string;
  numberWorkersOthers: string;
  numberWorkersToFind: string;
  fullProfile: boolean;
  nameComercial: string;
  typeService: string;
  url: string;
  description: string;
  sectoreId: number;
  subsectoreId: number;
  active: boolean;

  isAdminProfile?: boolean;
  isPsychologistProfile?: boolean;
  isBusinessProfile?: boolean;
  isAgentProfile?: boolean;
  last_singin?:string
}
