import { IFilterShowOpts } from "@apptypes/entities/IFilter";


const vacancyFilters: IFilterShowOpts = {
    availabilityToRelocation: true,
    availabilityToTravel: true,
    confidentialCompany: true,
    educationalLevelId: true,
    peopleDiscapacity: true,
    searchUniversity: false,
    yearsExperience: true,
    contractTypeId: true,
    searchQuery: true,
    seeVHByUser: false,
    company: true,
    maxLength: true,
    countryId: true,
    stateId: true,
    cityId: true,
    workdayId: true,
    minAge: true,
    maxAge: true,
    minSalary: true,
    maxSalary: true,
    profilePicture: false,
    drivingLicenseId: true,
    contractDate: true,
    createdAt: false,
    sectorId: true,
    availability: true,
    languages: true,
    userTypeId: true,
    studying: false,
    location: false
}

const userFilters: IFilterShowOpts = {
    company: false,
    confidentialCompany: false,
    contractDate: false,
    contractTypeId: false,
    availabilityToRelocation: true,
    availabilityToTravel: true,
    educationalLevelId: true,
    peopleDiscapacity: true,
    searchUniversity: true,
    yearsExperience: true,
    searchQuery: true,
    seeVHByUser: true,
    maxLength: true,
    countryId: true,
    stateId: true,
    cityId: true,
    workdayId: true,
    minAge: true,
    maxAge: true,
    minSalary: true,
    maxSalary: true,
    profilePicture: true,
    drivingLicenseId: true,
    createdAt: true,
    sectorId: true,
    availability: true,
    languages: true,
    userTypeId: false,
    studying: true,
    location: true
}

const requisitionBusinessFilters: IFilterShowOpts = {
    availabilityToRelocation: true,
    availabilityToTravel: true,
    confidentialCompany: false,
    educationalLevelId: true,
    peopleDiscapacity: true,
    searchUniversity: false,
    yearsExperience: true,
    contractTypeId: true,
    searchQuery: true,
    seeVHByUser: false,
    company: false,
    maxLength: true,
    countryId: true,
    stateId: true,
    cityId: true,
    workdayId: true,
    minAge: true,
    maxAge: true,
    minSalary: true,
    maxSalary: true,
    profilePicture: false,
    drivingLicenseId: true,
    contractDate: true,
    createdAt: false,
    sectorId: true,
    availability: true,
    languages: true,
    userTypeId: false,
    studying: false,
    location: false
}

const filterOpts = {
    vacancyFilters,
    userFilters,
    requisitionBusinessFilters,
    requisitionAdminFilters: vacancyFilters
}
export default filterOpts;